-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "ServiceItemType" ADD VALUE 'FILTER_ANNUAL_INSPECTION';
ALTER TYPE "ServiceItemType" ADD VALUE 'FILTER_EW_SENSOR_INSPECTION';
ALTER TYPE "ServiceItemType" ADD VALUE 'TANKER_PRESSURE_TEST';
ALTER TYPE "ServiceItemType" ADD VALUE 'TANKER_FIRE_SAFETY_TEST';
ALTER TYPE "ServiceItemType" ADD VALUE 'TANKER_CALIBRATION';
ALTER TYPE "ServiceItemType" ADD VALUE 'CONDUCTIVITY_METER_CALIBRATION';
ALTER TYPE "ServiceItemType" ADD VALUE 'HYDROMETER_CALIBRATION';
ALTER TYPE "ServiceItemType" ADD VALUE 'MAIN_FLOW_METER_CALIBRATION';
ALTER TYPE "ServiceItemType" ADD VALUE 'RESISTANCE_METER_CALIBRATION';
ALTER TYPE "ServiceItemType" ADD VALUE 'THERMOMETER_CALIBRATION';
ALTER TYPE "ServiceItemType" ADD VALUE 'TORQUE_WRENCH_CALIBRATION';
ALTER TYPE "ServiceItemType" ADD VALUE 'OVERWING_HOSE_TEST';
ALTER TYPE "ServiceItemType" ADD VALUE 'UNDERWING_HOSE_TEST';
ALTER TYPE "ServiceItemType" ADD VALUE 'HD38_PRESSURE_TEST';
ALTER TYPE "ServiceItemType" ADD VALUE 'HD63_PRESSURE_TEST';
ALTER TYPE "ServiceItemType" ADD VALUE 'TW75_PRESSURE_TEST';
ALTER TYPE "ServiceItemType" ADD VALUE 'QUARTERLY_INSPECTION';
ALTER TYPE "ServiceItemType" ADD VALUE 'WATER_CHEMICAL_TEST';
ALTER TYPE "ServiceItemType" ADD VALUE 'TACHOGRAPH_CALIBRATION';
ALTER TYPE "ServiceItemType" ADD VALUE 'ADR_CERTIFICATION';
ALTER TYPE "ServiceItemType" ADD VALUE 'CWD_EXPIRY';
